package ebs.hmw.gooProBuf.sub;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: subscriptions.proto

public final class ProtoSub {
  private ProtoSub() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoSubscriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:subscriptions.ProtoSubscription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string company = 2;</code>
     */
    String getCompany();
    /**
     * <code>string company = 2;</code>
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>string companySign = 3;</code>
     */
    String getCompanySign();
    /**
     * <code>string companySign = 3;</code>
     */
    com.google.protobuf.ByteString
        getCompanySignBytes();

    /**
     * <code>double value = 4;</code>
     */
    double getValue();

    /**
     * <code>string valueSign = 5;</code>
     */
    String getValueSign();
    /**
     * <code>string valueSign = 5;</code>
     */
    com.google.protobuf.ByteString
        getValueSignBytes();

    /**
     * <code>double variation = 6;</code>
     */
    double getVariation();

    /**
     * <code>string variationSign = 7;</code>
     */
    String getVariationSign();
    /**
     * <code>string variationSign = 7;</code>
     */
    com.google.protobuf.ByteString
        getVariationSignBytes();
  }
  /**
   * Protobuf type {@code subscriptions.ProtoSubscription}
   */
  public  static final class ProtoSubscription extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:subscriptions.ProtoSubscription)
      ProtoSubscriptionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoSubscription.newBuilder() to construct.
    private ProtoSubscription(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoSubscription() {
      id_ = 0;
      company_ = "";
      companySign_ = "";
      value_ = 0D;
      valueSign_ = "";
      variation_ = 0D;
      variationSign_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoSubscription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              company_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              companySign_ = s;
              break;
            }
            case 33: {

              value_ = input.readDouble();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              valueSign_ = s;
              break;
            }
            case 49: {

              variation_ = input.readDouble();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              variationSign_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoSub.internal_static_subscriptions_ProtoSubscription_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoSub.internal_static_subscriptions_ProtoSubscription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoSubscription.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int COMPANY_FIELD_NUMBER = 2;
    private volatile Object company_;
    /**
     * <code>string company = 2;</code>
     */
    public String getCompany() {
      Object ref = company_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <code>string company = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMPANYSIGN_FIELD_NUMBER = 3;
    private volatile Object companySign_;
    /**
     * <code>string companySign = 3;</code>
     */
    public String getCompanySign() {
      Object ref = companySign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        companySign_ = s;
        return s;
      }
    }
    /**
     * <code>string companySign = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCompanySignBytes() {
      Object ref = companySign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        companySign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 4;
    private double value_;
    /**
     * <code>double value = 4;</code>
     */
    public double getValue() {
      return value_;
    }

    public static final int VALUESIGN_FIELD_NUMBER = 5;
    private volatile Object valueSign_;
    /**
     * <code>string valueSign = 5;</code>
     */
    public String getValueSign() {
      Object ref = valueSign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        valueSign_ = s;
        return s;
      }
    }
    /**
     * <code>string valueSign = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValueSignBytes() {
      Object ref = valueSign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        valueSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VARIATION_FIELD_NUMBER = 6;
    private double variation_;
    /**
     * <code>double variation = 6;</code>
     */
    public double getVariation() {
      return variation_;
    }

    public static final int VARIATIONSIGN_FIELD_NUMBER = 7;
    private volatile Object variationSign_;
    /**
     * <code>string variationSign = 7;</code>
     */
    public String getVariationSign() {
      Object ref = variationSign_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        variationSign_ = s;
        return s;
      }
    }
    /**
     * <code>string variationSign = 7;</code>
     */
    public com.google.protobuf.ByteString
        getVariationSignBytes() {
      Object ref = variationSign_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        variationSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getCompanyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
      }
      if (!getCompanySignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, companySign_);
      }
      if (value_ != 0D) {
        output.writeDouble(4, value_);
      }
      if (!getValueSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, valueSign_);
      }
      if (variation_ != 0D) {
        output.writeDouble(6, variation_);
      }
      if (!getVariationSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, variationSign_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getCompanyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
      }
      if (!getCompanySignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, companySign_);
      }
      if (value_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, value_);
      }
      if (!getValueSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, valueSign_);
      }
      if (variation_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, variation_);
      }
      if (!getVariationSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, variationSign_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoSubscription)) {
        return super.equals(obj);
      }
      ProtoSubscription other = (ProtoSubscription) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getCompany()
          .equals(other.getCompany());
      result = result && getCompanySign()
          .equals(other.getCompanySign());
      result = result && (
          Double.doubleToLongBits(getValue())
          == Double.doubleToLongBits(
              other.getValue()));
      result = result && getValueSign()
          .equals(other.getValueSign());
      result = result && (
          Double.doubleToLongBits(getVariation())
          == Double.doubleToLongBits(
              other.getVariation()));
      result = result && getVariationSign()
          .equals(other.getVariationSign());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + COMPANYSIGN_FIELD_NUMBER;
      hash = (53 * hash) + getCompanySign().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getValue()));
      hash = (37 * hash) + VALUESIGN_FIELD_NUMBER;
      hash = (53 * hash) + getValueSign().hashCode();
      hash = (37 * hash) + VARIATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getVariation()));
      hash = (37 * hash) + VARIATIONSIGN_FIELD_NUMBER;
      hash = (53 * hash) + getVariationSign().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoSubscription parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoSubscription parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoSubscription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoSubscription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoSubscription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoSubscription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoSubscription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoSubscription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoSubscription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoSubscription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoSubscription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoSubscription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoSubscription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code subscriptions.ProtoSubscription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:subscriptions.ProtoSubscription)
        ProtoSubscriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoSub.internal_static_subscriptions_ProtoSubscription_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoSub.internal_static_subscriptions_ProtoSubscription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoSubscription.class, Builder.class);
      }

      // Construct using ProtoSub.ProtoSubscription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        company_ = "";

        companySign_ = "";

        value_ = 0D;

        valueSign_ = "";

        variation_ = 0D;

        variationSign_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoSub.internal_static_subscriptions_ProtoSubscription_descriptor;
      }

      public ProtoSubscription getDefaultInstanceForType() {
        return ProtoSubscription.getDefaultInstance();
      }

      public ProtoSubscription build() {
        ProtoSubscription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoSubscription buildPartial() {
        ProtoSubscription result = new ProtoSubscription(this);
        result.id_ = id_;
        result.company_ = company_;
        result.companySign_ = companySign_;
        result.value_ = value_;
        result.valueSign_ = valueSign_;
        result.variation_ = variation_;
        result.variationSign_ = variationSign_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoSubscription) {
          return mergeFrom((ProtoSubscription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoSubscription other) {
        if (other == ProtoSubscription.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          onChanged();
        }
        if (!other.getCompanySign().isEmpty()) {
          companySign_ = other.companySign_;
          onChanged();
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (!other.getValueSign().isEmpty()) {
          valueSign_ = other.valueSign_;
          onChanged();
        }
        if (other.getVariation() != 0D) {
          setVariation(other.getVariation());
        }
        if (!other.getVariationSign().isEmpty()) {
          variationSign_ = other.variationSign_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoSubscription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoSubscription) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private Object company_ = "";
      /**
       * <code>string company = 2;</code>
       */
      public String getCompany() {
        Object ref = company_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string company = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company = 2;</code>
       */
      public Builder setCompany(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string company = 2;</code>
       */
      public Builder clearCompany() {
        
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>string company = 2;</code>
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        company_ = value;
        onChanged();
        return this;
      }

      private Object companySign_ = "";
      /**
       * <code>string companySign = 3;</code>
       */
      public String getCompanySign() {
        Object ref = companySign_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          companySign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string companySign = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCompanySignBytes() {
        Object ref = companySign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          companySign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string companySign = 3;</code>
       */
      public Builder setCompanySign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        companySign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string companySign = 3;</code>
       */
      public Builder clearCompanySign() {
        
        companySign_ = getDefaultInstance().getCompanySign();
        onChanged();
        return this;
      }
      /**
       * <code>string companySign = 3;</code>
       */
      public Builder setCompanySignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        companySign_ = value;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 4;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 4;</code>
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 4;</code>
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }

      private Object valueSign_ = "";
      /**
       * <code>string valueSign = 5;</code>
       */
      public String getValueSign() {
        Object ref = valueSign_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          valueSign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string valueSign = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValueSignBytes() {
        Object ref = valueSign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          valueSign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string valueSign = 5;</code>
       */
      public Builder setValueSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        valueSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string valueSign = 5;</code>
       */
      public Builder clearValueSign() {
        
        valueSign_ = getDefaultInstance().getValueSign();
        onChanged();
        return this;
      }
      /**
       * <code>string valueSign = 5;</code>
       */
      public Builder setValueSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        valueSign_ = value;
        onChanged();
        return this;
      }

      private double variation_ ;
      /**
       * <code>double variation = 6;</code>
       */
      public double getVariation() {
        return variation_;
      }
      /**
       * <code>double variation = 6;</code>
       */
      public Builder setVariation(double value) {
        
        variation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double variation = 6;</code>
       */
      public Builder clearVariation() {
        
        variation_ = 0D;
        onChanged();
        return this;
      }

      private Object variationSign_ = "";
      /**
       * <code>string variationSign = 7;</code>
       */
      public String getVariationSign() {
        Object ref = variationSign_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          variationSign_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string variationSign = 7;</code>
       */
      public com.google.protobuf.ByteString
          getVariationSignBytes() {
        Object ref = variationSign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          variationSign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string variationSign = 7;</code>
       */
      public Builder setVariationSign(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        variationSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string variationSign = 7;</code>
       */
      public Builder clearVariationSign() {
        
        variationSign_ = getDefaultInstance().getVariationSign();
        onChanged();
        return this;
      }
      /**
       * <code>string variationSign = 7;</code>
       */
      public Builder setVariationSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        variationSign_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:subscriptions.ProtoSubscription)
    }

    // @@protoc_insertion_point(class_scope:subscriptions.ProtoSubscription)
    private static final ProtoSubscription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoSubscription();
    }

    public static ProtoSubscription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoSubscription>
        PARSER = new com.google.protobuf.AbstractParser<ProtoSubscription>() {
      public ProtoSubscription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoSubscription(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoSubscription> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoSubscription> getParserForType() {
      return PARSER;
    }

    public ProtoSubscription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtoSubscriptionListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:subscriptions.ProtoSubscriptionList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    java.util.List<ProtoSubscription>
        getSubscriptionList();
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    ProtoSubscription getSubscription(int index);
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    int getSubscriptionCount();
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    java.util.List<? extends ProtoSubscriptionOrBuilder>
        getSubscriptionOrBuilderList();
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    ProtoSubscriptionOrBuilder getSubscriptionOrBuilder(int index);
  }
  /**
   * Protobuf type {@code subscriptions.ProtoSubscriptionList}
   */
  public  static final class ProtoSubscriptionList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:subscriptions.ProtoSubscriptionList)
      ProtoSubscriptionListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoSubscriptionList.newBuilder() to construct.
    private ProtoSubscriptionList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoSubscriptionList() {
      subscription_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoSubscriptionList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                subscription_ = new java.util.ArrayList<ProtoSubscription>();
                mutable_bitField0_ |= 0x00000001;
              }
              subscription_.add(
                  input.readMessage(ProtoSubscription.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          subscription_ = java.util.Collections.unmodifiableList(subscription_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoSub.internal_static_subscriptions_ProtoSubscriptionList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoSub.internal_static_subscriptions_ProtoSubscriptionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoSubscriptionList.class, Builder.class);
    }

    public static final int SUBSCRIPTION_FIELD_NUMBER = 1;
    private java.util.List<ProtoSubscription> subscription_;
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    public java.util.List<ProtoSubscription> getSubscriptionList() {
      return subscription_;
    }
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    public java.util.List<? extends ProtoSubscriptionOrBuilder>
        getSubscriptionOrBuilderList() {
      return subscription_;
    }
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    public int getSubscriptionCount() {
      return subscription_.size();
    }
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    public ProtoSubscription getSubscription(int index) {
      return subscription_.get(index);
    }
    /**
     * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
     */
    public ProtoSubscriptionOrBuilder getSubscriptionOrBuilder(
        int index) {
      return subscription_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < subscription_.size(); i++) {
        output.writeMessage(1, subscription_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < subscription_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, subscription_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoSubscriptionList)) {
        return super.equals(obj);
      }
      ProtoSubscriptionList other = (ProtoSubscriptionList) obj;

      boolean result = true;
      result = result && getSubscriptionList()
          .equals(other.getSubscriptionList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSubscriptionCount() > 0) {
        hash = (37 * hash) + SUBSCRIPTION_FIELD_NUMBER;
        hash = (53 * hash) + getSubscriptionList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoSubscriptionList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoSubscriptionList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoSubscriptionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoSubscriptionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoSubscriptionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoSubscriptionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoSubscriptionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoSubscriptionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoSubscriptionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoSubscriptionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoSubscriptionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoSubscriptionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoSubscriptionList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code subscriptions.ProtoSubscriptionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:subscriptions.ProtoSubscriptionList)
        ProtoSubscriptionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoSub.internal_static_subscriptions_ProtoSubscriptionList_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoSub.internal_static_subscriptions_ProtoSubscriptionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoSubscriptionList.class, Builder.class);
      }

      // Construct using ProtoSub.ProtoSubscriptionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSubscriptionFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (subscriptionBuilder_ == null) {
          subscription_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          subscriptionBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoSub.internal_static_subscriptions_ProtoSubscriptionList_descriptor;
      }

      public ProtoSubscriptionList getDefaultInstanceForType() {
        return ProtoSubscriptionList.getDefaultInstance();
      }

      public ProtoSubscriptionList build() {
        ProtoSubscriptionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoSubscriptionList buildPartial() {
        ProtoSubscriptionList result = new ProtoSubscriptionList(this);
        int from_bitField0_ = bitField0_;
        if (subscriptionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            subscription_ = java.util.Collections.unmodifiableList(subscription_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.subscription_ = subscription_;
        } else {
          result.subscription_ = subscriptionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoSubscriptionList) {
          return mergeFrom((ProtoSubscriptionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoSubscriptionList other) {
        if (other == ProtoSubscriptionList.getDefaultInstance()) return this;
        if (subscriptionBuilder_ == null) {
          if (!other.subscription_.isEmpty()) {
            if (subscription_.isEmpty()) {
              subscription_ = other.subscription_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSubscriptionIsMutable();
              subscription_.addAll(other.subscription_);
            }
            onChanged();
          }
        } else {
          if (!other.subscription_.isEmpty()) {
            if (subscriptionBuilder_.isEmpty()) {
              subscriptionBuilder_.dispose();
              subscriptionBuilder_ = null;
              subscription_ = other.subscription_;
              bitField0_ = (bitField0_ & ~0x00000001);
              subscriptionBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSubscriptionFieldBuilder() : null;
            } else {
              subscriptionBuilder_.addAllMessages(other.subscription_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoSubscriptionList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoSubscriptionList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ProtoSubscription> subscription_ =
        java.util.Collections.emptyList();
      private void ensureSubscriptionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          subscription_ = new java.util.ArrayList<ProtoSubscription>(subscription_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoSubscription, ProtoSubscription.Builder, ProtoSubscriptionOrBuilder> subscriptionBuilder_;

      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public java.util.List<ProtoSubscription> getSubscriptionList() {
        if (subscriptionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(subscription_);
        } else {
          return subscriptionBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public int getSubscriptionCount() {
        if (subscriptionBuilder_ == null) {
          return subscription_.size();
        } else {
          return subscriptionBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public ProtoSubscription getSubscription(int index) {
        if (subscriptionBuilder_ == null) {
          return subscription_.get(index);
        } else {
          return subscriptionBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder setSubscription(
          int index, ProtoSubscription value) {
        if (subscriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscriptionIsMutable();
          subscription_.set(index, value);
          onChanged();
        } else {
          subscriptionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder setSubscription(
          int index, ProtoSubscription.Builder builderForValue) {
        if (subscriptionBuilder_ == null) {
          ensureSubscriptionIsMutable();
          subscription_.set(index, builderForValue.build());
          onChanged();
        } else {
          subscriptionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder addSubscription(ProtoSubscription value) {
        if (subscriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscriptionIsMutable();
          subscription_.add(value);
          onChanged();
        } else {
          subscriptionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder addSubscription(
          int index, ProtoSubscription value) {
        if (subscriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSubscriptionIsMutable();
          subscription_.add(index, value);
          onChanged();
        } else {
          subscriptionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder addSubscription(
          ProtoSubscription.Builder builderForValue) {
        if (subscriptionBuilder_ == null) {
          ensureSubscriptionIsMutable();
          subscription_.add(builderForValue.build());
          onChanged();
        } else {
          subscriptionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder addSubscription(
          int index, ProtoSubscription.Builder builderForValue) {
        if (subscriptionBuilder_ == null) {
          ensureSubscriptionIsMutable();
          subscription_.add(index, builderForValue.build());
          onChanged();
        } else {
          subscriptionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder addAllSubscription(
          Iterable<? extends ProtoSubscription> values) {
        if (subscriptionBuilder_ == null) {
          ensureSubscriptionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, subscription_);
          onChanged();
        } else {
          subscriptionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder clearSubscription() {
        if (subscriptionBuilder_ == null) {
          subscription_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          subscriptionBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public Builder removeSubscription(int index) {
        if (subscriptionBuilder_ == null) {
          ensureSubscriptionIsMutable();
          subscription_.remove(index);
          onChanged();
        } else {
          subscriptionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public ProtoSubscription.Builder getSubscriptionBuilder(
          int index) {
        return getSubscriptionFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public ProtoSubscriptionOrBuilder getSubscriptionOrBuilder(
          int index) {
        if (subscriptionBuilder_ == null) {
          return subscription_.get(index);  } else {
          return subscriptionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public java.util.List<? extends ProtoSubscriptionOrBuilder>
           getSubscriptionOrBuilderList() {
        if (subscriptionBuilder_ != null) {
          return subscriptionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(subscription_);
        }
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public ProtoSubscription.Builder addSubscriptionBuilder() {
        return getSubscriptionFieldBuilder().addBuilder(
            ProtoSubscription.getDefaultInstance());
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public ProtoSubscription.Builder addSubscriptionBuilder(
          int index) {
        return getSubscriptionFieldBuilder().addBuilder(
            index, ProtoSubscription.getDefaultInstance());
      }
      /**
       * <code>repeated .subscriptions.ProtoSubscription subscription = 1;</code>
       */
      public java.util.List<ProtoSubscription.Builder>
           getSubscriptionBuilderList() {
        return getSubscriptionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoSubscription, ProtoSubscription.Builder, ProtoSubscriptionOrBuilder>
          getSubscriptionFieldBuilder() {
        if (subscriptionBuilder_ == null) {
          subscriptionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoSubscription, ProtoSubscription.Builder, ProtoSubscriptionOrBuilder>(
                  subscription_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          subscription_ = null;
        }
        return subscriptionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:subscriptions.ProtoSubscriptionList)
    }

    // @@protoc_insertion_point(class_scope:subscriptions.ProtoSubscriptionList)
    private static final ProtoSubscriptionList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoSubscriptionList();
    }

    public static ProtoSubscriptionList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoSubscriptionList>
        PARSER = new com.google.protobuf.AbstractParser<ProtoSubscriptionList>() {
      public ProtoSubscriptionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoSubscriptionList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoSubscriptionList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoSubscriptionList> getParserForType() {
      return PARSER;
    }

    public ProtoSubscriptionList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptions_ProtoSubscription_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptions_ProtoSubscription_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_subscriptions_ProtoSubscriptionList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_subscriptions_ProtoSubscriptionList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023subscriptions.proto\022\rsubscriptions\"\221\001\n" +
      "\021ProtoSubscription\022\n\n\002id\030\001 \001(\005\022\017\n\007compan" +
      "y\030\002 \001(\t\022\023\n\013companySign\030\003 \001(\t\022\r\n\005value\030\004 " +
      "\001(\001\022\021\n\tvalueSign\030\005 \001(\t\022\021\n\tvariation\030\006 \001(" +
      "\001\022\025\n\rvariationSign\030\007 \001(\t\"O\n\025ProtoSubscri" +
      "ptionList\0226\n\014subscription\030\001 \003(\0132 .subscr" +
      "iptions.ProtoSubscriptionB\014\n\000B\010ProtoSubb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_subscriptions_ProtoSubscription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_subscriptions_ProtoSubscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptions_ProtoSubscription_descriptor,
        new String[] { "Id", "Company", "CompanySign", "Value", "ValueSign", "Variation", "VariationSign", });
    internal_static_subscriptions_ProtoSubscriptionList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_subscriptions_ProtoSubscriptionList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_subscriptions_ProtoSubscriptionList_descriptor,
        new String[] { "Subscription", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
