package ebs.hmw.gooProBuf.pub;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: publications.proto

public final class ProtoPub {
  private ProtoPub() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoPublicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:publications.ProtoPublication)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string company = 2;</code>
     */
    String getCompany();
    /**
     * <code>string company = 2;</code>
     */
    com.google.protobuf.ByteString
        getCompanyBytes();

    /**
     * <code>double value = 3;</code>
     */
    double getValue();

    /**
     * <code>double variation = 4;</code>
     */
    double getVariation();

    /**
     * <code>double drop = 5;</code>
     */
    double getDrop();
  }
  /**
   * Protobuf type {@code publications.ProtoPublication}
   */
  public  static final class ProtoPublication extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:publications.ProtoPublication)
      ProtoPublicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoPublication.newBuilder() to construct.
    private ProtoPublication(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoPublication() {
      id_ = 0;
      company_ = "";
      value_ = 0D;
      variation_ = 0D;
      drop_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoPublication(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              company_ = s;
              break;
            }
            case 25: {

              value_ = input.readDouble();
              break;
            }
            case 33: {

              variation_ = input.readDouble();
              break;
            }
            case 41: {

              drop_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoPub.internal_static_publications_ProtoPublication_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoPub.internal_static_publications_ProtoPublication_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoPublication.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int COMPANY_FIELD_NUMBER = 2;
    private volatile Object company_;
    /**
     * <code>string company = 2;</code>
     */
    public String getCompany() {
      Object ref = company_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        company_ = s;
        return s;
      }
    }
    /**
     * <code>string company = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyBytes() {
      Object ref = company_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        company_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private double value_;
    /**
     * <code>double value = 3;</code>
     */
    public double getValue() {
      return value_;
    }

    public static final int VARIATION_FIELD_NUMBER = 4;
    private double variation_;
    /**
     * <code>double variation = 4;</code>
     */
    public double getVariation() {
      return variation_;
    }

    public static final int DROP_FIELD_NUMBER = 5;
    private double drop_;
    /**
     * <code>double drop = 5;</code>
     */
    public double getDrop() {
      return drop_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getCompanyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, company_);
      }
      if (value_ != 0D) {
        output.writeDouble(3, value_);
      }
      if (variation_ != 0D) {
        output.writeDouble(4, variation_);
      }
      if (drop_ != 0D) {
        output.writeDouble(5, drop_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getCompanyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, company_);
      }
      if (value_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, value_);
      }
      if (variation_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, variation_);
      }
      if (drop_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, drop_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoPublication)) {
        return super.equals(obj);
      }
      ProtoPublication other = (ProtoPublication) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getCompany()
          .equals(other.getCompany());
      result = result && (
          Double.doubleToLongBits(getValue())
          == Double.doubleToLongBits(
              other.getValue()));
      result = result && (
          Double.doubleToLongBits(getVariation())
          == Double.doubleToLongBits(
              other.getVariation()));
      result = result && (
          Double.doubleToLongBits(getDrop())
          == Double.doubleToLongBits(
              other.getDrop()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getValue()));
      hash = (37 * hash) + VARIATION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getVariation()));
      hash = (37 * hash) + DROP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDrop()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoPublication parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoPublication parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoPublication parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoPublication parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoPublication parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoPublication parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoPublication parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoPublication parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoPublication parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoPublication parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoPublication parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoPublication parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoPublication prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code publications.ProtoPublication}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:publications.ProtoPublication)
        ProtoPublicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoPub.internal_static_publications_ProtoPublication_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoPub.internal_static_publications_ProtoPublication_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoPublication.class, Builder.class);
      }

      // Construct using ProtoPub.ProtoPublication.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        company_ = "";

        value_ = 0D;

        variation_ = 0D;

        drop_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoPub.internal_static_publications_ProtoPublication_descriptor;
      }

      public ProtoPublication getDefaultInstanceForType() {
        return ProtoPublication.getDefaultInstance();
      }

      public ProtoPublication build() {
        ProtoPublication result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoPublication buildPartial() {
        ProtoPublication result = new ProtoPublication(this);
        result.id_ = id_;
        result.company_ = company_;
        result.value_ = value_;
        result.variation_ = variation_;
        result.drop_ = drop_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoPublication) {
          return mergeFrom((ProtoPublication)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoPublication other) {
        if (other == ProtoPublication.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getCompany().isEmpty()) {
          company_ = other.company_;
          onChanged();
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        if (other.getVariation() != 0D) {
          setVariation(other.getVariation());
        }
        if (other.getDrop() != 0D) {
          setDrop(other.getDrop());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoPublication parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoPublication) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private Object company_ = "";
      /**
       * <code>string company = 2;</code>
       */
      public String getCompany() {
        Object ref = company_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          company_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string company = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyBytes() {
        Object ref = company_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          company_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string company = 2;</code>
       */
      public Builder setCompany(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        company_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string company = 2;</code>
       */
      public Builder clearCompany() {
        
        company_ = getDefaultInstance().getCompany();
        onChanged();
        return this;
      }
      /**
       * <code>string company = 2;</code>
       */
      public Builder setCompanyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        company_ = value;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 3;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 3;</code>
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 3;</code>
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }

      private double variation_ ;
      /**
       * <code>double variation = 4;</code>
       */
      public double getVariation() {
        return variation_;
      }
      /**
       * <code>double variation = 4;</code>
       */
      public Builder setVariation(double value) {
        
        variation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double variation = 4;</code>
       */
      public Builder clearVariation() {
        
        variation_ = 0D;
        onChanged();
        return this;
      }

      private double drop_ ;
      /**
       * <code>double drop = 5;</code>
       */
      public double getDrop() {
        return drop_;
      }
      /**
       * <code>double drop = 5;</code>
       */
      public Builder setDrop(double value) {
        
        drop_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double drop = 5;</code>
       */
      public Builder clearDrop() {
        
        drop_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:publications.ProtoPublication)
    }

    // @@protoc_insertion_point(class_scope:publications.ProtoPublication)
    private static final ProtoPublication DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoPublication();
    }

    public static ProtoPublication getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoPublication>
        PARSER = new com.google.protobuf.AbstractParser<ProtoPublication>() {
      public ProtoPublication parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPublication(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoPublication> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoPublication> getParserForType() {
      return PARSER;
    }

    public ProtoPublication getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProtoPublicationListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:publications.ProtoPublicationList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    java.util.List<ProtoPublication>
        getPublicationList();
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    ProtoPublication getPublication(int index);
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    int getPublicationCount();
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    java.util.List<? extends ProtoPublicationOrBuilder>
        getPublicationOrBuilderList();
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    ProtoPublicationOrBuilder getPublicationOrBuilder(int index);
  }
  /**
   * Protobuf type {@code publications.ProtoPublicationList}
   */
  public  static final class ProtoPublicationList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:publications.ProtoPublicationList)
      ProtoPublicationListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoPublicationList.newBuilder() to construct.
    private ProtoPublicationList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoPublicationList() {
      publication_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoPublicationList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                publication_ = new java.util.ArrayList<ProtoPublication>();
                mutable_bitField0_ |= 0x00000001;
              }
              publication_.add(
                  input.readMessage(ProtoPublication.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          publication_ = java.util.Collections.unmodifiableList(publication_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoPub.internal_static_publications_ProtoPublicationList_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoPub.internal_static_publications_ProtoPublicationList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoPublicationList.class, Builder.class);
    }

    public static final int PUBLICATION_FIELD_NUMBER = 1;
    private java.util.List<ProtoPublication> publication_;
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    public java.util.List<ProtoPublication> getPublicationList() {
      return publication_;
    }
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    public java.util.List<? extends ProtoPublicationOrBuilder>
        getPublicationOrBuilderList() {
      return publication_;
    }
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    public int getPublicationCount() {
      return publication_.size();
    }
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    public ProtoPublication getPublication(int index) {
      return publication_.get(index);
    }
    /**
     * <code>repeated .publications.ProtoPublication publication = 1;</code>
     */
    public ProtoPublicationOrBuilder getPublicationOrBuilder(
        int index) {
      return publication_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < publication_.size(); i++) {
        output.writeMessage(1, publication_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < publication_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, publication_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoPublicationList)) {
        return super.equals(obj);
      }
      ProtoPublicationList other = (ProtoPublicationList) obj;

      boolean result = true;
      result = result && getPublicationList()
          .equals(other.getPublicationList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPublicationCount() > 0) {
        hash = (37 * hash) + PUBLICATION_FIELD_NUMBER;
        hash = (53 * hash) + getPublicationList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoPublicationList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoPublicationList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoPublicationList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoPublicationList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoPublicationList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoPublicationList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoPublicationList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoPublicationList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoPublicationList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoPublicationList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoPublicationList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoPublicationList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoPublicationList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code publications.ProtoPublicationList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:publications.ProtoPublicationList)
        ProtoPublicationListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoPub.internal_static_publications_ProtoPublicationList_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoPub.internal_static_publications_ProtoPublicationList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoPublicationList.class, Builder.class);
      }

      // Construct using ProtoPub.ProtoPublicationList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPublicationFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (publicationBuilder_ == null) {
          publication_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          publicationBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoPub.internal_static_publications_ProtoPublicationList_descriptor;
      }

      public ProtoPublicationList getDefaultInstanceForType() {
        return ProtoPublicationList.getDefaultInstance();
      }

      public ProtoPublicationList build() {
        ProtoPublicationList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProtoPublicationList buildPartial() {
        ProtoPublicationList result = new ProtoPublicationList(this);
        int from_bitField0_ = bitField0_;
        if (publicationBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            publication_ = java.util.Collections.unmodifiableList(publication_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.publication_ = publication_;
        } else {
          result.publication_ = publicationBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoPublicationList) {
          return mergeFrom((ProtoPublicationList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoPublicationList other) {
        if (other == ProtoPublicationList.getDefaultInstance()) return this;
        if (publicationBuilder_ == null) {
          if (!other.publication_.isEmpty()) {
            if (publication_.isEmpty()) {
              publication_ = other.publication_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePublicationIsMutable();
              publication_.addAll(other.publication_);
            }
            onChanged();
          }
        } else {
          if (!other.publication_.isEmpty()) {
            if (publicationBuilder_.isEmpty()) {
              publicationBuilder_.dispose();
              publicationBuilder_ = null;
              publication_ = other.publication_;
              bitField0_ = (bitField0_ & ~0x00000001);
              publicationBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPublicationFieldBuilder() : null;
            } else {
              publicationBuilder_.addAllMessages(other.publication_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoPublicationList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoPublicationList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ProtoPublication> publication_ =
        java.util.Collections.emptyList();
      private void ensurePublicationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          publication_ = new java.util.ArrayList<ProtoPublication>(publication_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoPublication, ProtoPublication.Builder, ProtoPublicationOrBuilder> publicationBuilder_;

      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public java.util.List<ProtoPublication> getPublicationList() {
        if (publicationBuilder_ == null) {
          return java.util.Collections.unmodifiableList(publication_);
        } else {
          return publicationBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public int getPublicationCount() {
        if (publicationBuilder_ == null) {
          return publication_.size();
        } else {
          return publicationBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public ProtoPublication getPublication(int index) {
        if (publicationBuilder_ == null) {
          return publication_.get(index);
        } else {
          return publicationBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder setPublication(
          int index, ProtoPublication value) {
        if (publicationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePublicationIsMutable();
          publication_.set(index, value);
          onChanged();
        } else {
          publicationBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder setPublication(
          int index, ProtoPublication.Builder builderForValue) {
        if (publicationBuilder_ == null) {
          ensurePublicationIsMutable();
          publication_.set(index, builderForValue.build());
          onChanged();
        } else {
          publicationBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder addPublication(ProtoPublication value) {
        if (publicationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePublicationIsMutable();
          publication_.add(value);
          onChanged();
        } else {
          publicationBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder addPublication(
          int index, ProtoPublication value) {
        if (publicationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePublicationIsMutable();
          publication_.add(index, value);
          onChanged();
        } else {
          publicationBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder addPublication(
          ProtoPublication.Builder builderForValue) {
        if (publicationBuilder_ == null) {
          ensurePublicationIsMutable();
          publication_.add(builderForValue.build());
          onChanged();
        } else {
          publicationBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder addPublication(
          int index, ProtoPublication.Builder builderForValue) {
        if (publicationBuilder_ == null) {
          ensurePublicationIsMutable();
          publication_.add(index, builderForValue.build());
          onChanged();
        } else {
          publicationBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder addAllPublication(
          Iterable<? extends ProtoPublication> values) {
        if (publicationBuilder_ == null) {
          ensurePublicationIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, publication_);
          onChanged();
        } else {
          publicationBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder clearPublication() {
        if (publicationBuilder_ == null) {
          publication_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          publicationBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public Builder removePublication(int index) {
        if (publicationBuilder_ == null) {
          ensurePublicationIsMutable();
          publication_.remove(index);
          onChanged();
        } else {
          publicationBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public ProtoPublication.Builder getPublicationBuilder(
          int index) {
        return getPublicationFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public ProtoPublicationOrBuilder getPublicationOrBuilder(
          int index) {
        if (publicationBuilder_ == null) {
          return publication_.get(index);  } else {
          return publicationBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public java.util.List<? extends ProtoPublicationOrBuilder>
           getPublicationOrBuilderList() {
        if (publicationBuilder_ != null) {
          return publicationBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(publication_);
        }
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public ProtoPublication.Builder addPublicationBuilder() {
        return getPublicationFieldBuilder().addBuilder(
            ProtoPublication.getDefaultInstance());
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public ProtoPublication.Builder addPublicationBuilder(
          int index) {
        return getPublicationFieldBuilder().addBuilder(
            index, ProtoPublication.getDefaultInstance());
      }
      /**
       * <code>repeated .publications.ProtoPublication publication = 1;</code>
       */
      public java.util.List<ProtoPublication.Builder>
           getPublicationBuilderList() {
        return getPublicationFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoPublication, ProtoPublication.Builder, ProtoPublicationOrBuilder>
          getPublicationFieldBuilder() {
        if (publicationBuilder_ == null) {
          publicationBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoPublication, ProtoPublication.Builder, ProtoPublicationOrBuilder>(
                  publication_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          publication_ = null;
        }
        return publicationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:publications.ProtoPublicationList)
    }

    // @@protoc_insertion_point(class_scope:publications.ProtoPublicationList)
    private static final ProtoPublicationList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoPublicationList();
    }

    public static ProtoPublicationList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProtoPublicationList>
        PARSER = new com.google.protobuf.AbstractParser<ProtoPublicationList>() {
      public ProtoPublicationList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPublicationList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoPublicationList> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProtoPublicationList> getParserForType() {
      return PARSER;
    }

    public ProtoPublicationList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_publications_ProtoPublication_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_publications_ProtoPublication_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_publications_ProtoPublicationList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_publications_ProtoPublicationList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022publications.proto\022\014publications\"_\n\020Pr" +
      "otoPublication\022\n\n\002id\030\001 \001(\005\022\017\n\007company\030\002 " +
      "\001(\t\022\r\n\005value\030\003 \001(\001\022\021\n\tvariation\030\004 \001(\001\022\014\n" +
      "\004drop\030\005 \001(\001\"K\n\024ProtoPublicationList\0223\n\013p" +
      "ublication\030\001 \003(\0132\036.publications.ProtoPub" +
      "licationB\014\n\000B\010ProtoPubb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_publications_ProtoPublication_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_publications_ProtoPublication_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_publications_ProtoPublication_descriptor,
        new String[] { "Id", "Company", "Value", "Variation", "Drop", });
    internal_static_publications_ProtoPublicationList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_publications_ProtoPublicationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_publications_ProtoPublicationList_descriptor,
        new String[] { "Publication", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
